title: Jane Black's Homepage
page-top-title: Jane Black
top-section-bg-text: Computer Science
home-subtitle: Jane Black&ensp;|&ensp;fork
copyright-text: '&copy; Jane Black 2023-2024. All Rights Reserved.'
